// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [23:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [23:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [23:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
output  [23:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [23:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [23:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [23:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg[23:0] res_V_data_0_V_din;
reg res_V_data_0_V_write;
reg[23:0] res_V_data_1_V_din;
reg res_V_data_1_V_write;
reg[23:0] res_V_data_2_V_din;
reg res_V_data_2_V_write;
reg[23:0] res_V_data_3_V_din;
reg res_V_data_3_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln37_fu_208_p2;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    res_V_data_0_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln42_fu_240_p2;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
wire   [5:0] i_fu_214_p2;
wire    io_acc_block_signal_op21;
wire    io_acc_block_signal_op26;
reg    ap_block_state2;
wire   [1:0] i_4_fu_246_p2;
wire    io_acc_block_signal_op35;
reg    ap_block_state3;
reg   [5:0] i1_0_reg_186;
wire    io_acc_block_signal_op13;
reg    ap_block_state1;
reg   [1:0] i2_0_reg_197;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i1_0_reg_186 <= 6'd0;
    end else if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_186 <= i_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i2_0_reg_197 <= 2'd0;
    end else if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i2_0_reg_197 <= i_4_fu_246_p2;
    end
end

always @ (*) begin
    if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((((icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        res_V_data_0_V_din = data_V_data_0_V_dout;
    end else if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_0_V_din = 24'd0;
    end else begin
        res_V_data_0_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        res_V_data_1_V_din = data_V_data_1_V_dout;
    end else if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_1_V_din = 24'd0;
    end else begin
        res_V_data_1_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        res_V_data_2_V_din = data_V_data_2_V_dout;
    end else if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_2_V_din = 24'd0;
    end else begin
        res_V_data_2_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        res_V_data_3_V_din = data_V_data_3_V_dout;
    end else if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_3_V_din = 24'd0;
    end else begin
        res_V_data_3_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~(((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0))) & (icmp_ln37_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0)) & (icmp_ln42_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (io_acc_block_signal_op13 == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op26 == 1'b0)) | ((icmp_ln37_fu_208_p2 == 1'd0) & (io_acc_block_signal_op21 == 1'b0)));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln42_fu_240_p2 == 1'd0) & (io_acc_block_signal_op35 == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign i_4_fu_246_p2 = (i2_0_reg_197 + 2'd1);

assign i_fu_214_p2 = (i1_0_reg_186 + 6'd1);

assign icmp_ln37_fu_208_p2 = ((i1_0_reg_186 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_240_p2 = ((i2_0_reg_197 == 2'd2) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op13 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op21 = (data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_0_V_empty_n);

assign io_acc_block_signal_op26 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op35 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign start_out = real_start;

endmodule //zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_s
