#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 20 19:03:44 +03 2024
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_nand_flash_controller_wrapper_behav -key {Behavioral:sim_1:Functional:tb_nand_flash_controller_wrapper} -tclbatch tb_nand_flash_controller_wrapper.tcl -view /home/berkb/project_3/encoder_tb_behav.wcfg -log simulate.log"
xsim tb_nand_flash_controller_wrapper_behav -key {Behavioral:sim_1:Functional:tb_nand_flash_controller_wrapper} -tclbatch tb_nand_flash_controller_wrapper.tcl -view /home/berkb/project_3/encoder_tb_behav.wcfg -log simulate.log

