# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/berkb/project_3/project_3.runs/synth_1/top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tlffg1156-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/berkb/project_3/project_3.cache/wt [current_project]
set_property parent.project_path /home/berkb/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/berkb/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11cud.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/Encoder.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_16s_7s_23_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_common.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d1_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_6s_30_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_activation_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_array.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d35_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w11.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_helpers.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_resource.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w5.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_image.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv1d_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d67_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s_w11_V.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_16s_8s_24_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_embed_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/hls_math.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s_w2_V.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2bkb.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/ACMP_smul_ss.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_activation.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b11.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/hls_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_math.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_recr_activations.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_merge.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_ref.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_pooling.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_padding_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/AESL_pkg.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_base.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_image_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_latency.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/utils/x_hls_utils.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/defines.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s_w5_V.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_7s_31_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b5.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_8s_32_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv2d_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w16_d66_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/etc/ap_private.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b2.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s_w15_V.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_garnet.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_ref.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_shift_reg.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w15.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_types.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_resource.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_recurrent.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_special.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_base.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d32_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_decl.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_batchnorm_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w2.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_batchnorm.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_special.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_8s_24s_32_1_1.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_common.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/parameters.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_mult.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b15.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_compressed.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_resource.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_ap_int_16_1u_array_ap_int_16_1u_config18_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s_w8_V.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b8.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_pooling_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_code_gen.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_latency.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d64_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d16_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_embed.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_merge_stream.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_latency.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_U0.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_padding.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d68_A.h
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w8.h
}
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11cud.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/Encoder.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_16s_7s_23_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_common.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d1_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_6s_30_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_activation_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_array.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d35_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w11.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_helpers.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_resource.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w5.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_image.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv1d_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d67_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s_w11_V.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_16s_8s_24_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_embed_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/hls_math.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s_w2_V.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2bkb.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/ACMP_smul_ss.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_activation.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b11.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/hls_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_math.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_recr_activations.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_merge.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_ref.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_pooling.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_padding_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/AESL_pkg.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_base.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_image_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv2d_latency.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/utils/x_hls_utils.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/defines.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s_w5_V.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_7s_31_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b5.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_24s_8s_32_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_sepconv2d_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w16_d66_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/etc/ap_private.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b2.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s_w15_V.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_garnet.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_ref.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_shift_reg.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w15.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_types.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_resource.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_recurrent.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_int_special.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_base.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d32_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_decl.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_batchnorm_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w2.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_batchnorm.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed_special.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/Encoder_mul_mul_8s_24s_32_1_1.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_common.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/parameters.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_mult.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b15.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/ap_types/ap_fixed.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_compressed.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_resource.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/zeropad1d_cl_array_ap_int_16_1u_array_ap_int_16_1u_config18_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s_w8_V.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/b8.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_pooling_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_code_gen.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_latency.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d64_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d16_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_embed.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_dense_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_merge_stream.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_conv1d_latency.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/start_for_linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_U0.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/nnet_utils/nnet_padding.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/syn/systemc/fifo_w24_d68_A.h]
set_property file_type "Verilog Header" [get_files /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/firmware/weights/w8.h]
read_verilog -library xil_defaultlib -sv /home/berkb/project_3/project_3.srcs/sources_1/new/controlOnfi.sv
read_vhdl -library xil_defaultlib {
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_16s_7s_23_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_16s_8s_24_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_24s_6s_30_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_24s_7s_31_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_24s_8s_32_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder_mul_mul_8s_24s_32_1_1.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11_s_w11_V.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_s_w8_V.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_s_w5_V.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2_s_w2_V.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/dense_wrapper_ap_fixed_24_16_0_0_0_ap_fixed_24_16_0_0_0_config15_s_w15_V.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w16_d66_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d16_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d1_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d32_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d35_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d64_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d67_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/fifo_w24_d68_A.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/regslice_core.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_conv_1d_cl_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_4u_config11cud.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_4u_config8_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_24_16_0_0_0_8u_config5_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_conv_1d_cl_array_ap_int_16_1u_array_ap_fixed_24_16_0_0_0_8u_config2bkb.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_dense_array_ap_fixed_4u_array_ap_fixed_24_16_0_0_0_16u_config15_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_linear_array_array_ap_fixed_16_16_0_0_0_16u_linear_config17_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/start_for_zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_U0.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/zeropad1d_cl_array_ap_int_16_1u_array_ap_int_16_1u_config18_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_4u_config21_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config19_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/zeropad1d_cl_array_array_ap_fixed_24_16_0_0_0_8u_config20_s.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/hls4ml_prj/Encoder_prj/solution1/impl/vhdl/Encoder.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/new/onfi_wrapper.vhd
  /home/berkb/project_3/project_3.srcs/sources_1/imports/new/top_wrapper.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/berkb/project_3/project_3.srcs/constrs_1/imports/project_3/impl_1.xdc
set_property used_in_implementation false [get_files /home/berkb/project_3/project_3.srcs/constrs_1/imports/project_3/impl_1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_wrapper -part xc7a200tlffg1156-2L
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
